# -*- coding: utf-8 -*-
"""Untitled149.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baMOZEj4csHcYmGepO0by24RKdW6r6D3
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
df=pd.read_csv('/content/spam mail (5).csv')
# Convert labels to numbers
df['Category'] = df['Category'].map({'ham': 0, 'spam': 1})
print(df)
X_train, X_test, y_train, y_test = train_test_split(
    df['Masseges'], df['Category'], test_size=0.2, random_state=42
)

vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# Predictions
y_pred = model.predict(X_test_vec)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
email = ["Hello brother how are you and when we meet "]
email_vec = vectorizer.transform(email)
prediction = model.predict(email_vec)

print("Spam" if prediction[0] == 1 else "Not Spam")